
package buurtservice.berichten;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import buurtservice.berichten.request.BuurtServiceRequest;
import buurtservice.berichten.response.BuurtServiceResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS-Interface", targetNamespace = "http://buurtservice/berichten/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    buurtservice.berichten.error.ObjectFactory.class,
    buurtservice.berichten.request.ObjectFactory.class,
    buurtservice.berichten.response.ObjectFactory.class
})
public interface WSInterface {


    /**
     * 
     * @param parameters
     * @return
     *     returns buurtservice.berichten.response.BuurtServiceResponse
     * @throws ApplicatieFout
     */
    @WebMethod
    @WebResult(name = "BuurtService-response", targetNamespace = "http://buurtservice/berichten/response", partName = "response")
    public BuurtServiceResponse getInwoners(
        @WebParam(name = "BuurtService-request", targetNamespace = "http://buurtservice/berichten/request", partName = "parameters")
        BuurtServiceRequest parameters)
        throws ApplicatieFout
    ;

}
